# Example Site settings

google_analytics: UA-171497613-2

header_pages:
  - index.md
  - about.md
  - lh1008.md
  - contact.md

footer: 'check my <a href="https://github.com/lh1008/" target="_blank">github</a><br>'
footer1: 'check my <a href="https://www.linkedin.com/in/lh1008/" target="_blank">linkedin</a>'

style: light # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
#theme: jekyll-theme-console
remote_theme: b2a3e8/jekyll-theme-console
