# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - about.md
  - lh1008.md
  - contact.md

footer: 'follow me on <a href="https://twitter.com/lh1008">twitter</a><br>'
footer1: 'check my <a href="https://github.com/lh1008/">github</a><br>'
footer2: 'check my <a href="https://www.linkedin.com/in/lh1008/">linkedin</a>'

style: light # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
theme: jekyll-theme-console
#remote_theme: b2a3e8/jekyll-theme-console
